Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,5 +1,3 @@
-name: Docker CI/CD
-
 on:
   push:
     branches:
@@ -11,7 +9,7 @@ jobs:
 
     env:
       DOCKER_IMAGE_NAME: my-html
-      
+
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
@@ -29,36 +27,18 @@ jobs:
 
       - name: Set up SSH and Deploy
         run: |
-         echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/private_key
-         chmod 600 /tmp/private_key
-         eval "$(ssh-agent -s)"
-         ssh-add /tmp/private_key
+          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/private_key
+          chmod 600 /tmp/private_key
         env:
-         SSH_AUTH_SOCK: /tmp/ssh-agent.sock
-
-      - name: Connect to Remote Server and Docker Login
-        run: |
-            ssh -v -o StrictHostKeyChecking=no -i /tmp/private_key ${{ secrets.SSH_USERNAME }}@${{ secrets.SWARM_MANAGER_IP }} 'docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}'
-            exit_code=$?
-            echo $exit_code > exit_code_login.txt
-        shell: /bin/bash
-
-      - name: Check Docker Login Output
-        run: cat exit_code_login.txt
-        if: failure()
+          SSH_AUTH_SOCK: /tmp/ssh-agent.sock
 
       - name: Copy Docker Compose file to remote server
         run: |
-         scp -o StrictHostKeyChecking=no -i /tmp/private_key docker-compose.yml "${{ secrets.SSH_USERNAME }}@${{ secrets.SWARM_MANAGER_IP }}:/tmp" || true
-         ssh -o StrictHostKeyChecking=no -i /tmp/private_key ${{ secrets.SSH_USERNAME }}@${{ secrets.SWARM_MANAGER_IP }} 'chmod +x /tmp/docker-compose.yml && ls -l /tmp && cat /tmp/docker-compose.yml' || true
+          scp -o StrictHostKeyChecking=no -i /tmp/private_key docker-compose.yml "${{ secrets.SSH_USERNAME }}@${{ secrets.SWARM_MANAGER_IP }}:/tmp" || true
+          ssh -o StrictHostKeyChecking=no -i /tmp/private_key ${{ secrets.SSH_USERNAME }}@${{ secrets.SWARM_MANAGER_IP }} 'chmod +x /tmp/docker-compose.yml && ls -l /tmp && cat /tmp/docker-compose.yml' || true
 
       - name: Connect to Remote Server and Deploy
         run: |
-         ssh -v -o StrictHostKeyChecking=no -i /tmp/private_key ${{ secrets.SSH_USERNAME }}@${{ secrets.SWARM_MANAGER_IP }} 'docker stack deploy -c /tmp/docker-compose.yml myapp'
-         exit_code=$?
-         echo $exit_code > exit_code_deploy.txt
-         shell: /bin/bash
-
-      - name: Check Deploy Output
-        run: cat exit_code_deploy.txt
-        if: failure()
+          ssh -v -o StrictHostKeyChecking=no -i /tmp/private_key ${{ secrets.SSH_USERNAME }}@${{ secrets.SWARM_MANAGER_IP }} 'docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} && echo "Docker login successful" && docker stack deploy -c docker-compose.yml myapp && echo "Docker stack deploy successful" || echo "Docker stack deploy failed"' 2>&1 | tee deployment_output.txt
+          sleep 10  # Add a delay to allow time for services to start
+          cat deployment_output.txt
